sudo: required
services:
  - docker 
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # DECRYPT GOOGLE CLOUD AUTH
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # INSTALL GOOGLE CLOUD SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sk/path.bash.inc
  - gcloud components update kubectl 
  # SETUP GOOGLE CLOUD AUTH
  - gcloud auth activate-service-account --key-file service-account.json
  # SETUP COMPUTE ZONE, PROJECT & CLUSTER
  - gcloud config set project keen-answer-303200
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  # LOGIN INTO DOCKER
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # BUILD TEST IMAGE
  - docker build -t cw729/react-test -f ./client/Dockerfile.dev ./client

script:
  # RUN REACT TEST IMAGE
  - docker run -e CI=true cw729/react-test npm test
script:
  # RUN REACT TEST IMAGE
  - docker run -e CI=true cw729/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master