sudo: required
services:
  - docker 
before_install:
  # DECRYPT GOOGLE CLOUD AUTH
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # INSTALL GOOGLE CLOUD SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sk/path.bash.inc
  - gcloud components update kubectl 
  # SETUP GOOGLE CLOUD AUTH
  - gcloud auth activate-service-account --key-file service-account.json
